version: "3"

services:
  user_service:
    build:
      context: ./user
      dockerfile: ./user/dockerfile
    ports:
      - "3000:3000"

  wallet_service:
    build:
      context: ./wallet
      dockerfile: ./wallet/dockerfile
    ports:
      - "3001:3001"

  transaction_service:
    build:
      context: ./transaction
      dockerfile: ./transaction/dockerfile
    ports:
      - "3002:3002"

  notification_service:
    build:
      context: ./transaction
      dockerfile: ./transaction/dockerfile
    ports:
      - "3002:3002"
